//
//  TestChatLoginViewController.swift
//  ColorgyCourse
//
//  Created by David on 2016/1/25.
//  Copyright © 2016年 David. All rights reserved.
//

import UIKit

class TestChatLoginViewController: UIViewController {
	
	@IBAction func  test_yuntech_student_ca62() {
		self.statusLabel.text = "切換中..."
		ColorgyLogin.loginToColorgyWithUsername(username: "test-yzu-student-f478@test.colorgy.io", password: "test-yzu-student-f478", success: { (result) -> Void in
			ColorgyAPI.me({ (result) -> Void in
				UserSetting.storeAPIMeResult(result: result)
				self.statusLabel.text = "你現在是 \(UserSetting.UserPossibleOrganization())的學生"
				}, failure: { () -> Void in
					
			})
			}) { () -> Void in
			
		}
	}
	
	@IBAction func test_yzu_student_f478() {
		self.statusLabel.text = "切換中..."
		ColorgyLogin.loginToColorgyWithUsername(username: "test-yuntech-student-ca62@test.colorgy.io", password: "test-yuntech-student-ca62", success: { (result) -> Void in
			ColorgyAPI.me({ (result) -> Void in
				UserSetting.storeAPIMeResult(result: result)
				self.statusLabel.text = "你現在是 \(UserSetting.UserPossibleOrganization())的學生"
				}, failure: { () -> Void in
					
			})
			}) { () -> Void in
				
		}
	}
	
	func generalLogin(n: String, p: String) {
		self.statusLabel.text = "切換中..."
		ColorgyLogin.loginToColorgyWithUsername(username: n, password: p, success: { (result) -> Void in
			ColorgyAPI.me({ (result) -> Void in
				UserSetting.storeAPIMeResult(result: result)
				self.statusLabel.text = "你現在是 \(UserSetting.UserPossibleOrganization())的學生"
				}, failure: { () -> Void in
					
			})
			}) { () -> Void in
				
		}
	}
	
	@IBOutlet weak var statusLabel: UILabel!
	
	override func viewDidDisappear(animated: Bool) {
		super.viewDidDisappear(animated)
		hidesBottomBarWhenPushed = false
	}
	
	override func viewDidAppear(animated: Bool) {
		super.viewDidAppear(animated)
		statusLabel.text = "你現在是 \(UserSetting.UserPossibleOrganization())的學生"
	}
	
	var userId: String!
	var accesstoken: String!
	var friendId: String!
	var uuid: String!

	var testAccounts: [[String]] = [["colorgy-test-account-1@test.colorgy.io", "colorgy-test-account-1"],
		["colorgy-test-account-2@test.colorgy.io", "colorgy-test-account-2"],
		["colorgy-test-account-3@test.colorgy.io", "colorgy-test-account-3"],
		["colorgy-test-account-4@test.colorgy.io", "colorgy-test-account-4"],
		["colorgy-test-account-5@test.colorgy.io", "colorgy-test-account-5"],
		["colorgy-test-account-6@test.colorgy.io", "colorgy-test-account-6"],
		["colorgy-test-account-7@test.colorgy.io", "colorgy-test-account-7"],
		["colorgy-test-account-8@test.colorgy.io", "colorgy-test-account-8"],
		["colorgy-test-account-9@test.colorgy.io", "colorgy-test-account-9"],
		["colorgy-test-account-10@test.colorgy.io", "colorgy-test-account-10"],
		["colorgy-test-account-11@test.colorgy.io", "colorgy-test-account-11"],
		["colorgy-test-account-12@test.colorgy.io", "colorgy-test-account-12"],
		["colorgy-test-account-13@test.colorgy.io", "colorgy-test-account-13"],
		["colorgy-test-account-14@test.colorgy.io", "colorgy-test-account-14"],
		["colorgy-test-account-15@test.colorgy.io", "colorgy-test-account-15"],
		["colorgy-test-account-16@test.colorgy.io", "colorgy-test-account-16"],
		["colorgy-test-account-17@test.colorgy.io", "colorgy-test-account-17"],
		["colorgy-test-account-18@test.colorgy.io", "colorgy-test-account-18"],
		["colorgy-test-account-19@test.colorgy.io", "colorgy-test-account-19"],
		["colorgy-test-account-20@test.colorgy.io", "colorgy-test-account-20"],
		["colorgy-test-account-21@test.colorgy.io", "colorgy-test-account-21"],
		["colorgy-test-account-22@test.colorgy.io", "colorgy-test-account-22"],
		["colorgy-test-account-23@test.colorgy.io", "colorgy-test-account-23"],
		["colorgy-test-account-24@test.colorgy.io", "colorgy-test-account-24"],
		["colorgy-test-account-25@test.colorgy.io", "colorgy-test-account-25"],
		["colorgy-test-account-26@test.colorgy.io", "colorgy-test-account-26"],
		["colorgy-test-account-27@test.colorgy.io", "colorgy-test-account-27"],
		["colorgy-test-account-28@test.colorgy.io", "colorgy-test-account-28"],
		["colorgy-test-account-29@test.colorgy.io", "colorgy-test-account-29"],
		["colorgy-test-account-30@test.colorgy.io", "colorgy-test-account-30"],
		["colorgy-test-account-31@test.colorgy.io", "colorgy-test-account-31"],
		["colorgy-test-account-32@test.colorgy.io", "colorgy-test-account-32"],
		["colorgy-test-account-33@test.colorgy.io", "colorgy-test-account-33"],
		["colorgy-test-account-34@test.colorgy.io", "colorgy-test-account-34"],
		["colorgy-test-account-35@test.colorgy.io", "colorgy-test-account-35"],
		["colorgy-test-account-36@test.colorgy.io", "colorgy-test-account-36"],
		["colorgy-test-account-37@test.colorgy.io", "colorgy-test-account-37"],
		["colorgy-test-account-38@test.colorgy.io", "colorgy-test-account-38"],
		["colorgy-test-account-39@test.colorgy.io", "colorgy-test-account-39"],
		["colorgy-test-account-40@test.colorgy.io", "colorgy-test-account-40"],
		["colorgy-test-account-41@test.colorgy.io", "colorgy-test-account-41"],
		["colorgy-test-account-42@test.colorgy.io", "colorgy-test-account-42"],
		["colorgy-test-account-43@test.colorgy.io", "colorgy-test-account-43"],
		["colorgy-test-account-44@test.colorgy.io", "colorgy-test-account-44"],
		["colorgy-test-account-45@test.colorgy.io", "colorgy-test-account-45"],
		["colorgy-test-account-46@test.colorgy.io", "colorgy-test-account-46"],
		["colorgy-test-account-47@test.colorgy.io", "colorgy-test-account-47"],
		["colorgy-test-account-48@test.colorgy.io", "colorgy-test-account-48"],
		["colorgy-test-account-49@test.colorgy.io", "colorgy-test-account-49"],
		["colorgy-test-account-50@test.colorgy.io", "colorgy-test-account-50"],
		["colorgy-test-account-51@test.colorgy.io", "colorgy-test-account-51"],
		["colorgy-test-account-52@test.colorgy.io", "colorgy-test-account-52"],
		["colorgy-test-account-53@test.colorgy.io", "colorgy-test-account-53"],
		["colorgy-test-account-54@test.colorgy.io", "colorgy-test-account-54"],
		["colorgy-test-account-55@test.colorgy.io", "colorgy-test-account-55"],
		["colorgy-test-account-56@test.colorgy.io", "colorgy-test-account-56"],
		["colorgy-test-account-57@test.colorgy.io", "colorgy-test-account-57"],
		["colorgy-test-account-58@test.colorgy.io", "colorgy-test-account-58"],
		["colorgy-test-account-59@test.colorgy.io", "colorgy-test-account-59"],
		["colorgy-test-account-60@test.colorgy.io", "colorgy-test-account-60"],
		["colorgy-test-account-61@test.colorgy.io", "colorgy-test-account-61"],
		["colorgy-test-account-62@test.colorgy.io", "colorgy-test-account-62"],
		["colorgy-test-account-63@test.colorgy.io", "colorgy-test-account-63"],
		["colorgy-test-account-64@test.colorgy.io", "colorgy-test-account-64"],
		["colorgy-test-account-65@test.colorgy.io", "colorgy-test-account-65"],
		["colorgy-test-account-66@test.colorgy.io", "colorgy-test-account-66"],
		["colorgy-test-account-67@test.colorgy.io", "colorgy-test-account-67"],
		["colorgy-test-account-68@test.colorgy.io", "colorgy-test-account-68"],
		["colorgy-test-account-69@test.colorgy.io", "colorgy-test-account-69"],
		["colorgy-test-account-70@test.colorgy.io", "colorgy-test-account-70"],
		["colorgy-test-account-71@test.colorgy.io", "colorgy-test-account-71"],
		["colorgy-test-account-72@test.colorgy.io", "colorgy-test-account-72"],
		["colorgy-test-account-73@test.colorgy.io", "colorgy-test-account-73"],
		["colorgy-test-account-74@test.colorgy.io", "colorgy-test-account-74"],
		["colorgy-test-account-75@test.colorgy.io", "colorgy-test-account-75"],
		["colorgy-test-account-76@test.colorgy.io", "colorgy-test-account-76"],
		["colorgy-test-account-77@test.colorgy.io", "colorgy-test-account-77"],
		["colorgy-test-account-78@test.colorgy.io", "colorgy-test-account-78"],
		["colorgy-test-account-79@test.colorgy.io", "colorgy-test-account-79"],
		["colorgy-test-account-80@test.colorgy.io", "colorgy-test-account-80"],
		["colorgy-test-account-81@test.colorgy.io", "colorgy-test-account-81"],
		["colorgy-test-account-82@test.colorgy.io", "colorgy-test-account-82"],
		["colorgy-test-account-83@test.colorgy.io", "colorgy-test-account-83"],
		["colorgy-test-account-84@test.colorgy.io", "colorgy-test-account-84"],
		["colorgy-test-account-85@test.colorgy.io", "colorgy-test-account-85"],
		["colorgy-test-account-86@test.colorgy.io", "colorgy-test-account-86"],
		["colorgy-test-account-87@test.colorgy.io", "colorgy-test-account-87"],
		["colorgy-test-account-88@test.colorgy.io", "colorgy-test-account-88"],
		["colorgy-test-account-89@test.colorgy.io", "colorgy-test-account-89"],
		["colorgy-test-account-90@test.colorgy.io", "colorgy-test-account-90"],
		["colorgy-test-account-91@test.colorgy.io", "colorgy-test-account-91"],
		["colorgy-test-account-92@test.colorgy.io", "colorgy-test-account-92"],
		["colorgy-test-account-93@test.colorgy.io", "colorgy-test-account-93"],
		["colorgy-test-account-94@test.colorgy.io", "colorgy-test-account-94"],
		["colorgy-test-account-95@test.colorgy.io", "colorgy-test-account-95"],
		["colorgy-test-account-96@test.colorgy.io", "colorgy-test-account-96"],
		["colorgy-test-account-97@test.colorgy.io", "colorgy-test-account-97"],
		["colorgy-test-account-98@test.colorgy.io", "colorgy-test-account-98"],
		["colorgy-test-account-99@test.colorgy.io", "colorgy-test-account-99"],
		["colorgy-test-account-100@test.colorgy.io", "colorgy-test-account-100"],
		["colorgy-test-account-101@test.colorgy.io", "colorgy-test-account-101"],
		["colorgy-test-account-102@test.colorgy.io", "colorgy-test-account-102"],
		["colorgy-test-account-103@test.colorgy.io", "colorgy-test-account-103"],
		["colorgy-test-account-104@test.colorgy.io", "colorgy-test-account-104"],
		["colorgy-test-account-105@test.colorgy.io", "colorgy-test-account-105"],
		["colorgy-test-account-106@test.colorgy.io", "colorgy-test-account-106"],
		["colorgy-test-account-107@test.colorgy.io", "colorgy-test-account-107"],
		["colorgy-test-account-108@test.colorgy.io", "colorgy-test-account-108"],
		["colorgy-test-account-109@test.colorgy.io", "colorgy-test-account-109"],
		["colorgy-test-account-110@test.colorgy.io", "colorgy-test-account-110"],
		["colorgy-test-account-111@test.colorgy.io", "colorgy-test-account-111"],
		["colorgy-test-account-112@test.colorgy.io", "colorgy-test-account-112"],
		["colorgy-test-account-113@test.colorgy.io", "colorgy-test-account-113"],
		["colorgy-test-account-114@test.colorgy.io", "colorgy-test-account-114"],
		["colorgy-test-account-115@test.colorgy.io", "colorgy-test-account-115"],
		["colorgy-test-account-116@test.colorgy.io", "colorgy-test-account-116"],
		["colorgy-test-account-117@test.colorgy.io", "colorgy-test-account-117"],
		["colorgy-test-account-118@test.colorgy.io", "colorgy-test-account-118"],
		["colorgy-test-account-119@test.colorgy.io", "colorgy-test-account-119"],
		["colorgy-test-account-120@test.colorgy.io", "colorgy-test-account-120"],
		["colorgy-test-account-121@test.colorgy.io", "colorgy-test-account-121"],
		["colorgy-test-account-122@test.colorgy.io", "colorgy-test-account-122"],
		["colorgy-test-account-123@test.colorgy.io", "colorgy-test-account-123"],
		["colorgy-test-account-124@test.colorgy.io", "colorgy-test-account-124"],
		["colorgy-test-account-125@test.colorgy.io", "colorgy-test-account-125"],
		["colorgy-test-account-126@test.colorgy.io", "colorgy-test-account-126"],
		["colorgy-test-account-127@test.colorgy.io", "colorgy-test-account-127"],
		["colorgy-test-account-128@test.colorgy.io", "colorgy-test-account-128"],
		["colorgy-test-account-129@test.colorgy.io", "colorgy-test-account-129"],
		["colorgy-test-account-130@test.colorgy.io", "colorgy-test-account-130"],
		["colorgy-test-account-131@test.colorgy.io", "colorgy-test-account-131"],
		["colorgy-test-account-132@test.colorgy.io", "colorgy-test-account-132"],
		["colorgy-test-account-133@test.colorgy.io", "colorgy-test-account-133"],
		["colorgy-test-account-134@test.colorgy.io", "colorgy-test-account-134"],
		["colorgy-test-account-135@test.colorgy.io", "colorgy-test-account-135"],
		["colorgy-test-account-136@test.colorgy.io", "colorgy-test-account-136"],
		["colorgy-test-account-137@test.colorgy.io", "colorgy-test-account-137"],
		["colorgy-test-account-138@test.colorgy.io", "colorgy-test-account-138"],
		["colorgy-test-account-139@test.colorgy.io", "colorgy-test-account-139"],
		["colorgy-test-account-140@test.colorgy.io", "colorgy-test-account-140"],
		["colorgy-test-account-141@test.colorgy.io", "colorgy-test-account-141"],
		["colorgy-test-account-142@test.colorgy.io", "colorgy-test-account-142"],
		["colorgy-test-account-143@test.colorgy.io", "colorgy-test-account-143"],
		["colorgy-test-account-144@test.colorgy.io", "colorgy-test-account-144"],
		["colorgy-test-account-145@test.colorgy.io", "colorgy-test-account-145"],
		["colorgy-test-account-146@test.colorgy.io", "colorgy-test-account-146"],
		["colorgy-test-account-147@test.colorgy.io", "colorgy-test-account-147"],
		["colorgy-test-account-148@test.colorgy.io", "colorgy-test-account-148"],
		["colorgy-test-account-149@test.colorgy.io", "colorgy-test-account-149"],
		["colorgy-test-account-150@test.colorgy.io", "colorgy-test-account-150"],
		["colorgy-test-account-151@test.colorgy.io", "colorgy-test-account-151"],
		["colorgy-test-account-152@test.colorgy.io", "colorgy-test-account-152"],
		["colorgy-test-account-153@test.colorgy.io", "colorgy-test-account-153"],
		["colorgy-test-account-154@test.colorgy.io", "colorgy-test-account-154"],
		["colorgy-test-account-155@test.colorgy.io", "colorgy-test-account-155"],
		["colorgy-test-account-156@test.colorgy.io", "colorgy-test-account-156"],
		["colorgy-test-account-157@test.colorgy.io", "colorgy-test-account-157"],
		["colorgy-test-account-158@test.colorgy.io", "colorgy-test-account-158"],
		["colorgy-test-account-159@test.colorgy.io", "colorgy-test-account-159"],
		["colorgy-test-account-160@test.colorgy.io", "colorgy-test-account-160"],
		["colorgy-test-account-161@test.colorgy.io", "colorgy-test-account-161"],
		["colorgy-test-account-162@test.colorgy.io", "colorgy-test-account-162"],
		["colorgy-test-account-163@test.colorgy.io", "colorgy-test-account-163"],
		["colorgy-test-account-164@test.colorgy.io", "colorgy-test-account-164"],
		["colorgy-test-account-165@test.colorgy.io", "colorgy-test-account-165"],
		["colorgy-test-account-166@test.colorgy.io", "colorgy-test-account-166"],
		["colorgy-test-account-167@test.colorgy.io", "colorgy-test-account-167"],
		["colorgy-test-account-168@test.colorgy.io", "colorgy-test-account-168"],
		["colorgy-test-account-169@test.colorgy.io", "colorgy-test-account-169"],
		["colorgy-test-account-170@test.colorgy.io", "colorgy-test-account-170"],
		["colorgy-test-account-171@test.colorgy.io", "colorgy-test-account-171"],
		["colorgy-test-account-172@test.colorgy.io", "colorgy-test-account-172"],
		["colorgy-test-account-173@test.colorgy.io", "colorgy-test-account-173"],
		["colorgy-test-account-174@test.colorgy.io", "colorgy-test-account-174"],
		["colorgy-test-account-175@test.colorgy.io", "colorgy-test-account-175"],
		["colorgy-test-account-176@test.colorgy.io", "colorgy-test-account-176"],
		["colorgy-test-account-177@test.colorgy.io", "colorgy-test-account-177"],
		["colorgy-test-account-178@test.colorgy.io", "colorgy-test-account-178"],
		["colorgy-test-account-179@test.colorgy.io", "colorgy-test-account-179"],
		["colorgy-test-account-180@test.colorgy.io", "colorgy-test-account-180"],
		["colorgy-test-account-181@test.colorgy.io", "colorgy-test-account-181"],
		["colorgy-test-account-182@test.colorgy.io", "colorgy-test-account-182"],
		["colorgy-test-account-183@test.colorgy.io", "colorgy-test-account-183"],
		["colorgy-test-account-184@test.colorgy.io", "colorgy-test-account-184"],
		["colorgy-test-account-185@test.colorgy.io", "colorgy-test-account-185"],
		["colorgy-test-account-186@test.colorgy.io", "colorgy-test-account-186"],
		["colorgy-test-account-187@test.colorgy.io", "colorgy-test-account-187"],
		["colorgy-test-account-188@test.colorgy.io", "colorgy-test-account-188"],
		["colorgy-test-account-189@test.colorgy.io", "colorgy-test-account-189"],
		["colorgy-test-account-190@test.colorgy.io", "colorgy-test-account-190"],
		["colorgy-test-account-191@test.colorgy.io", "colorgy-test-account-191"],
		["colorgy-test-account-192@test.colorgy.io", "colorgy-test-account-192"],
		["colorgy-test-account-193@test.colorgy.io", "colorgy-test-account-193"],
		["colorgy-test-account-194@test.colorgy.io", "colorgy-test-account-194"],
		["colorgy-test-account-195@test.colorgy.io", "colorgy-test-account-195"],
		["colorgy-test-account-196@test.colorgy.io", "colorgy-test-account-196"],
		["colorgy-test-account-197@test.colorgy.io", "colorgy-test-account-197"],
		["colorgy-test-account-198@test.colorgy.io", "colorgy-test-account-198"],
		["colorgy-test-account-199@test.colorgy.io", "colorgy-test-account-199"],
		["colorgy-test-account-200@test.colorgy.io", "colorgy-test-account-200"],
		["colorgy-test-account-201@test.colorgy.io", "colorgy-test-account-201"],
		["colorgy-test-account-202@test.colorgy.io", "colorgy-test-account-202"],
		["colorgy-test-account-203@test.colorgy.io", "colorgy-test-account-203"],
		["colorgy-test-account-204@test.colorgy.io", "colorgy-test-account-204"],
		["colorgy-test-account-205@test.colorgy.io", "colorgy-test-account-205"],
		["colorgy-test-account-206@test.colorgy.io", "colorgy-test-account-206"],
		["colorgy-test-account-207@test.colorgy.io", "colorgy-test-account-207"],
		["colorgy-test-account-208@test.colorgy.io", "colorgy-test-account-208"],
		["colorgy-test-account-209@test.colorgy.io", "colorgy-test-account-209"],
		["colorgy-test-account-210@test.colorgy.io", "colorgy-test-account-210"],
		["colorgy-test-account-211@test.colorgy.io", "colorgy-test-account-211"],
		["colorgy-test-account-212@test.colorgy.io", "colorgy-test-account-212"],
		["colorgy-test-account-213@test.colorgy.io", "colorgy-test-account-213"],
		["colorgy-test-account-214@test.colorgy.io", "colorgy-test-account-214"],
		["colorgy-test-account-215@test.colorgy.io", "colorgy-test-account-215"],
		["colorgy-test-account-216@test.colorgy.io", "colorgy-test-account-216"],
		["colorgy-test-account-217@test.colorgy.io", "colorgy-test-account-217"],
		["colorgy-test-account-218@test.colorgy.io", "colorgy-test-account-218"],
		["colorgy-test-account-219@test.colorgy.io", "colorgy-test-account-219"],
		["colorgy-test-account-220@test.colorgy.io", "colorgy-test-account-220"],
		["colorgy-test-account-221@test.colorgy.io", "colorgy-test-account-221"],
		["colorgy-test-account-222@test.colorgy.io", "colorgy-test-account-222"],
		["colorgy-test-account-223@test.colorgy.io", "colorgy-test-account-223"],
		["colorgy-test-account-224@test.colorgy.io", "colorgy-test-account-224"],
		["colorgy-test-account-225@test.colorgy.io", "colorgy-test-account-225"],
		["colorgy-test-account-226@test.colorgy.io", "colorgy-test-account-226"],
		["colorgy-test-account-227@test.colorgy.io", "colorgy-test-account-227"],
		["colorgy-test-account-228@test.colorgy.io", "colorgy-test-account-228"],
		["colorgy-test-account-229@test.colorgy.io", "colorgy-test-account-229"],
		["colorgy-test-account-230@test.colorgy.io", "colorgy-test-account-230"],
		["colorgy-test-account-231@test.colorgy.io", "colorgy-test-account-231"],
		["colorgy-test-account-232@test.colorgy.io", "colorgy-test-account-232"],
		["colorgy-test-account-233@test.colorgy.io", "colorgy-test-account-233"],
		["colorgy-test-account-234@test.colorgy.io", "colorgy-test-account-234"],
		["colorgy-test-account-235@test.colorgy.io", "colorgy-test-account-235"],
		["colorgy-test-account-236@test.colorgy.io", "colorgy-test-account-236"],
		["colorgy-test-account-237@test.colorgy.io", "colorgy-test-account-237"],
		["colorgy-test-account-238@test.colorgy.io", "colorgy-test-account-238"],
		["colorgy-test-account-239@test.colorgy.io", "colorgy-test-account-239"],
		["colorgy-test-account-240@test.colorgy.io", "colorgy-test-account-240"],
		["colorgy-test-account-241@test.colorgy.io", "colorgy-test-account-241"],
		["colorgy-test-account-242@test.colorgy.io", "colorgy-test-account-242"],
		["colorgy-test-account-243@test.colorgy.io", "colorgy-test-account-243"],
		["colorgy-test-account-244@test.colorgy.io", "colorgy-test-account-244"],
		["colorgy-test-account-245@test.colorgy.io", "colorgy-test-account-245"],
		["colorgy-test-account-246@test.colorgy.io", "colorgy-test-account-246"],
		["colorgy-test-account-247@test.colorgy.io", "colorgy-test-account-247"],
		["colorgy-test-account-248@test.colorgy.io", "colorgy-test-account-248"],
		["colorgy-test-account-249@test.colorgy.io", "colorgy-test-account-249"],
		["colorgy-test-account-250@test.colorgy.io", "colorgy-test-account-250"],
		["colorgy-test-account-251@test.colorgy.io", "colorgy-test-account-251"],
		["colorgy-test-account-252@test.colorgy.io", "colorgy-test-account-252"],
		["colorgy-test-account-253@test.colorgy.io", "colorgy-test-account-253"],
		["colorgy-test-account-254@test.colorgy.io", "colorgy-test-account-254"],
		["colorgy-test-account-255@test.colorgy.io", "colorgy-test-account-255"],
		["colorgy-test-account-256@test.colorgy.io", "colorgy-test-account-256"],
		["colorgy-test-account-257@test.colorgy.io", "colorgy-test-account-257"],
		["colorgy-test-account-258@test.colorgy.io", "colorgy-test-account-258"],
		["colorgy-test-account-259@test.colorgy.io", "colorgy-test-account-259"],
		["colorgy-test-account-260@test.colorgy.io", "colorgy-test-account-260"],
		["colorgy-test-account-261@test.colorgy.io", "colorgy-test-account-261"],
		["colorgy-test-account-262@test.colorgy.io", "colorgy-test-account-262"],
		["colorgy-test-account-263@test.colorgy.io", "colorgy-test-account-263"],
		["colorgy-test-account-264@test.colorgy.io", "colorgy-test-account-264"],
		["colorgy-test-account-265@test.colorgy.io", "colorgy-test-account-265"],
		["colorgy-test-account-266@test.colorgy.io", "colorgy-test-account-266"],
		["colorgy-test-account-267@test.colorgy.io", "colorgy-test-account-267"],
		["colorgy-test-account-268@test.colorgy.io", "colorgy-test-account-268"],
		["colorgy-test-account-269@test.colorgy.io", "colorgy-test-account-269"],
		["colorgy-test-account-270@test.colorgy.io", "colorgy-test-account-270"],
		["colorgy-test-account-271@test.colorgy.io", "colorgy-test-account-271"],
		["colorgy-test-account-272@test.colorgy.io", "colorgy-test-account-272"],
		["colorgy-test-account-273@test.colorgy.io", "colorgy-test-account-273"],
		["colorgy-test-account-274@test.colorgy.io", "colorgy-test-account-274"],
		["colorgy-test-account-275@test.colorgy.io", "colorgy-test-account-275"],
		["colorgy-test-account-276@test.colorgy.io", "colorgy-test-account-276"],
		["colorgy-test-account-277@test.colorgy.io", "colorgy-test-account-277"],
		["colorgy-test-account-278@test.colorgy.io", "colorgy-test-account-278"],
		["colorgy-test-account-279@test.colorgy.io", "colorgy-test-account-279"],
		["colorgy-test-account-280@test.colorgy.io", "colorgy-test-account-280"],
		["colorgy-test-account-281@test.colorgy.io", "colorgy-test-account-281"],
		["colorgy-test-account-282@test.colorgy.io", "colorgy-test-account-282"],
		["colorgy-test-account-283@test.colorgy.io", "colorgy-test-account-283"],
		["colorgy-test-account-284@test.colorgy.io", "colorgy-test-account-284"],
		["colorgy-test-account-285@test.colorgy.io", "colorgy-test-account-285"],
		["colorgy-test-account-286@test.colorgy.io", "colorgy-test-account-286"],
		["colorgy-test-account-287@test.colorgy.io", "colorgy-test-account-287"],
		["colorgy-test-account-288@test.colorgy.io", "colorgy-test-account-288"],
		["colorgy-test-account-289@test.colorgy.io", "colorgy-test-account-289"],
		["colorgy-test-account-290@test.colorgy.io", "colorgy-test-account-290"],
		["colorgy-test-account-291@test.colorgy.io", "colorgy-test-account-291"],
		["colorgy-test-account-292@test.colorgy.io", "colorgy-test-account-292"],
		["colorgy-test-account-293@test.colorgy.io", "colorgy-test-account-293"],
		["colorgy-test-account-294@test.colorgy.io", "colorgy-test-account-294"],
		["colorgy-test-account-295@test.colorgy.io", "colorgy-test-account-295"],
		["colorgy-test-account-296@test.colorgy.io", "colorgy-test-account-296"],
		["colorgy-test-account-297@test.colorgy.io", "colorgy-test-account-297"],
		["colorgy-test-account-298@test.colorgy.io", "colorgy-test-account-298"],
		["colorgy-test-account-299@test.colorgy.io", "colorgy-test-account-299"],
		["colorgy-test-account-300@test.colorgy.io", "colorgy-test-account-300"],
		["colorgy-test-account-301@test.colorgy.io", "colorgy-test-account-301"],
		["colorgy-test-account-302@test.colorgy.io", "colorgy-test-account-302"],
		["colorgy-test-account-303@test.colorgy.io", "colorgy-test-account-303"],
		["colorgy-test-account-304@test.colorgy.io", "colorgy-test-account-304"],
		["colorgy-test-account-305@test.colorgy.io", "colorgy-test-account-305"],
		["colorgy-test-account-306@test.colorgy.io", "colorgy-test-account-306"],
		["colorgy-test-account-307@test.colorgy.io", "colorgy-test-account-307"],
		["colorgy-test-account-308@test.colorgy.io", "colorgy-test-account-308"],
		["colorgy-test-account-309@test.colorgy.io", "colorgy-test-account-309"],
		["colorgy-test-account-310@test.colorgy.io", "colorgy-test-account-310"],
		["colorgy-test-account-311@test.colorgy.io", "colorgy-test-account-311"],
		["colorgy-test-account-312@test.colorgy.io", "colorgy-test-account-312"],
		["colorgy-test-account-313@test.colorgy.io", "colorgy-test-account-313"],
		["colorgy-test-account-314@test.colorgy.io", "colorgy-test-account-314"],
		["colorgy-test-account-315@test.colorgy.io", "colorgy-test-account-315"],
		["colorgy-test-account-316@test.colorgy.io", "colorgy-test-account-316"],
		["colorgy-test-account-317@test.colorgy.io", "colorgy-test-account-317"],
		["colorgy-test-account-318@test.colorgy.io", "colorgy-test-account-318"],
		["colorgy-test-account-319@test.colorgy.io", "colorgy-test-account-319"],
		["colorgy-test-account-320@test.colorgy.io", "colorgy-test-account-320"],
		["colorgy-test-account-321@test.colorgy.io", "colorgy-test-account-321"],
		["colorgy-test-account-322@test.colorgy.io", "colorgy-test-account-322"],
		["colorgy-test-account-323@test.colorgy.io", "colorgy-test-account-323"],
		["colorgy-test-account-324@test.colorgy.io", "colorgy-test-account-324"],
		["colorgy-test-account-325@test.colorgy.io", "colorgy-test-account-325"],
		["colorgy-test-account-326@test.colorgy.io", "colorgy-test-account-326"],
		["colorgy-test-account-327@test.colorgy.io", "colorgy-test-account-327"],
		["colorgy-test-account-328@test.colorgy.io", "colorgy-test-account-328"],
		["colorgy-test-account-329@test.colorgy.io", "colorgy-test-account-329"],
		["colorgy-test-account-330@test.colorgy.io", "colorgy-test-account-330"],
		["colorgy-test-account-331@test.colorgy.io", "colorgy-test-account-331"],
		["colorgy-test-account-332@test.colorgy.io", "colorgy-test-account-332"],
		["colorgy-test-account-333@test.colorgy.io", "colorgy-test-account-333"],
		["colorgy-test-account-334@test.colorgy.io", "colorgy-test-account-334"],
		["colorgy-test-account-335@test.colorgy.io", "colorgy-test-account-335"],
		["colorgy-test-account-336@test.colorgy.io", "colorgy-test-account-336"],
		["colorgy-test-account-337@test.colorgy.io", "colorgy-test-account-337"],
		["colorgy-test-account-338@test.colorgy.io", "colorgy-test-account-338"],
		["colorgy-test-account-339@test.colorgy.io", "colorgy-test-account-339"],
		["colorgy-test-account-340@test.colorgy.io", "colorgy-test-account-340"],
		["colorgy-test-account-341@test.colorgy.io", "colorgy-test-account-341"],
		["colorgy-test-account-342@test.colorgy.io", "colorgy-test-account-342"],
		["colorgy-test-account-343@test.colorgy.io", "colorgy-test-account-343"],
		["colorgy-test-account-344@test.colorgy.io", "colorgy-test-account-344"],
		["colorgy-test-account-345@test.colorgy.io", "colorgy-test-account-345"],
		["colorgy-test-account-346@test.colorgy.io", "colorgy-test-account-346"],
		["colorgy-test-account-347@test.colorgy.io", "colorgy-test-account-347"],
		["colorgy-test-account-348@test.colorgy.io", "colorgy-test-account-348"],
		["colorgy-test-account-349@test.colorgy.io", "colorgy-test-account-349"],
		["colorgy-test-account-350@test.colorgy.io", "colorgy-test-account-350"],
		["colorgy-test-account-351@test.colorgy.io", "colorgy-test-account-351"],
		["colorgy-test-account-352@test.colorgy.io", "colorgy-test-account-352"],
		["colorgy-test-account-353@test.colorgy.io", "colorgy-test-account-353"],
		["colorgy-test-account-354@test.colorgy.io", "colorgy-test-account-354"],
		["colorgy-test-account-355@test.colorgy.io", "colorgy-test-account-355"],
		["colorgy-test-account-356@test.colorgy.io", "colorgy-test-account-356"],
		["colorgy-test-account-357@test.colorgy.io", "colorgy-test-account-357"],
		["colorgy-test-account-358@test.colorgy.io", "colorgy-test-account-358"],
		["colorgy-test-account-359@test.colorgy.io", "colorgy-test-account-359"],
		["colorgy-test-account-360@test.colorgy.io", "colorgy-test-account-360"],
		["colorgy-test-account-361@test.colorgy.io", "colorgy-test-account-361"],
		["colorgy-test-account-362@test.colorgy.io", "colorgy-test-account-362"],
		["colorgy-test-account-363@test.colorgy.io", "colorgy-test-account-363"],
		["colorgy-test-account-364@test.colorgy.io", "colorgy-test-account-364"],
		["colorgy-test-account-365@test.colorgy.io", "colorgy-test-account-365"],
		["colorgy-test-account-366@test.colorgy.io", "colorgy-test-account-366"],
		["colorgy-test-account-367@test.colorgy.io", "colorgy-test-account-367"],
		["colorgy-test-account-368@test.colorgy.io", "colorgy-test-account-368"],
		["colorgy-test-account-369@test.colorgy.io", "colorgy-test-account-369"],
		["colorgy-test-account-370@test.colorgy.io", "colorgy-test-account-370"],
		["colorgy-test-account-371@test.colorgy.io", "colorgy-test-account-371"],
		["colorgy-test-account-372@test.colorgy.io", "colorgy-test-account-372"],
		["colorgy-test-account-373@test.colorgy.io", "colorgy-test-account-373"],
		["colorgy-test-account-374@test.colorgy.io", "colorgy-test-account-374"],
		["colorgy-test-account-375@test.colorgy.io", "colorgy-test-account-375"],
		["colorgy-test-account-376@test.colorgy.io", "colorgy-test-account-376"],
		["colorgy-test-account-377@test.colorgy.io", "colorgy-test-account-377"],
		["colorgy-test-account-378@test.colorgy.io", "colorgy-test-account-378"],
		["colorgy-test-account-379@test.colorgy.io", "colorgy-test-account-379"],
		["colorgy-test-account-380@test.colorgy.io", "colorgy-test-account-380"],
		["colorgy-test-account-381@test.colorgy.io", "colorgy-test-account-381"],
		["colorgy-test-account-382@test.colorgy.io", "colorgy-test-account-382"],
		["colorgy-test-account-383@test.colorgy.io", "colorgy-test-account-383"],
		["colorgy-test-account-384@test.colorgy.io", "colorgy-test-account-384"],
		["colorgy-test-account-385@test.colorgy.io", "colorgy-test-account-385"],
		["colorgy-test-account-386@test.colorgy.io", "colorgy-test-account-386"],
		["colorgy-test-account-387@test.colorgy.io", "colorgy-test-account-387"],
		["colorgy-test-account-388@test.colorgy.io", "colorgy-test-account-388"],
		["colorgy-test-account-389@test.colorgy.io", "colorgy-test-account-389"],
		["colorgy-test-account-390@test.colorgy.io", "colorgy-test-account-390"],
		["colorgy-test-account-391@test.colorgy.io", "colorgy-test-account-391"],
		["colorgy-test-account-392@test.colorgy.io", "colorgy-test-account-392"],
		["colorgy-test-account-393@test.colorgy.io", "colorgy-test-account-393"],
		["colorgy-test-account-394@test.colorgy.io", "colorgy-test-account-394"],
		["colorgy-test-account-395@test.colorgy.io", "colorgy-test-account-395"],
		["colorgy-test-account-396@test.colorgy.io", "colorgy-test-account-396"],
		["colorgy-test-account-397@test.colorgy.io", "colorgy-test-account-397"],
		["colorgy-test-account-398@test.colorgy.io", "colorgy-test-account-398"],
		["colorgy-test-account-399@test.colorgy.io", "colorgy-test-account-399"],
		["colorgy-test-account-400@test.colorgy.io", "colorgy-test-account-400"],
		["colorgy-test-account-401@test.colorgy.io", "colorgy-test-account-401"],
		["colorgy-test-account-402@test.colorgy.io", "colorgy-test-account-402"],
		["colorgy-test-account-403@test.colorgy.io", "colorgy-test-account-403"],
		["colorgy-test-account-404@test.colorgy.io", "colorgy-test-account-404"],
		["colorgy-test-account-405@test.colorgy.io", "colorgy-test-account-405"],
		["colorgy-test-account-406@test.colorgy.io", "colorgy-test-account-406"],
		["colorgy-test-account-407@test.colorgy.io", "colorgy-test-account-407"],
		["colorgy-test-account-408@test.colorgy.io", "colorgy-test-account-408"],
		["colorgy-test-account-409@test.colorgy.io", "colorgy-test-account-409"],
		["colorgy-test-account-410@test.colorgy.io", "colorgy-test-account-410"],
		["colorgy-test-account-411@test.colorgy.io", "colorgy-test-account-411"],
		["colorgy-test-account-412@test.colorgy.io", "colorgy-test-account-412"],
		["colorgy-test-account-413@test.colorgy.io", "colorgy-test-account-413"],
		["colorgy-test-account-414@test.colorgy.io", "colorgy-test-account-414"],
		["colorgy-test-account-415@test.colorgy.io", "colorgy-test-account-415"],
		["colorgy-test-account-416@test.colorgy.io", "colorgy-test-account-416"],
		["colorgy-test-account-417@test.colorgy.io", "colorgy-test-account-417"],
		["colorgy-test-account-418@test.colorgy.io", "colorgy-test-account-418"],
		["colorgy-test-account-419@test.colorgy.io", "colorgy-test-account-419"],
		["colorgy-test-account-420@test.colorgy.io", "colorgy-test-account-420"],
		["colorgy-test-account-421@test.colorgy.io", "colorgy-test-account-421"],
		["colorgy-test-account-422@test.colorgy.io", "colorgy-test-account-422"],
		["colorgy-test-account-423@test.colorgy.io", "colorgy-test-account-423"],
		["colorgy-test-account-424@test.colorgy.io", "colorgy-test-account-424"],
		["colorgy-test-account-425@test.colorgy.io", "colorgy-test-account-425"],
		["colorgy-test-account-426@test.colorgy.io", "colorgy-test-account-426"],
		["colorgy-test-account-427@test.colorgy.io", "colorgy-test-account-427"],
		["colorgy-test-account-428@test.colorgy.io", "colorgy-test-account-428"],
		["colorgy-test-account-429@test.colorgy.io", "colorgy-test-account-429"],
		["colorgy-test-account-430@test.colorgy.io", "colorgy-test-account-430"],
		["colorgy-test-account-431@test.colorgy.io", "colorgy-test-account-431"],
		["colorgy-test-account-432@test.colorgy.io", "colorgy-test-account-432"],
		["colorgy-test-account-433@test.colorgy.io", "colorgy-test-account-433"],
		["colorgy-test-account-434@test.colorgy.io", "colorgy-test-account-434"],
		["colorgy-test-account-435@test.colorgy.io", "colorgy-test-account-435"],
		["colorgy-test-account-436@test.colorgy.io", "colorgy-test-account-436"],
		["colorgy-test-account-437@test.colorgy.io", "colorgy-test-account-437"],
		["colorgy-test-account-438@test.colorgy.io", "colorgy-test-account-438"],
		["colorgy-test-account-439@test.colorgy.io", "colorgy-test-account-439"],
		["colorgy-test-account-440@test.colorgy.io", "colorgy-test-account-440"],
		["colorgy-test-account-441@test.colorgy.io", "colorgy-test-account-441"],
		["colorgy-test-account-442@test.colorgy.io", "colorgy-test-account-442"],
		["colorgy-test-account-443@test.colorgy.io", "colorgy-test-account-443"],
		["colorgy-test-account-444@test.colorgy.io", "colorgy-test-account-444"],
		["colorgy-test-account-445@test.colorgy.io", "colorgy-test-account-445"],
		["colorgy-test-account-446@test.colorgy.io", "colorgy-test-account-446"],
		["colorgy-test-account-447@test.colorgy.io", "colorgy-test-account-447"],
		["colorgy-test-account-448@test.colorgy.io", "colorgy-test-account-448"],
		["colorgy-test-account-449@test.colorgy.io", "colorgy-test-account-449"],
		["colorgy-test-account-450@test.colorgy.io", "colorgy-test-account-450"],
		["colorgy-test-account-451@test.colorgy.io", "colorgy-test-account-451"],
		["colorgy-test-account-452@test.colorgy.io", "colorgy-test-account-452"],
		["colorgy-test-account-453@test.colorgy.io", "colorgy-test-account-453"],
		["colorgy-test-account-454@test.colorgy.io", "colorgy-test-account-454"],
		["colorgy-test-account-455@test.colorgy.io", "colorgy-test-account-455"],
		["colorgy-test-account-456@test.colorgy.io", "colorgy-test-account-456"],
		["colorgy-test-account-457@test.colorgy.io", "colorgy-test-account-457"],
		["colorgy-test-account-458@test.colorgy.io", "colorgy-test-account-458"],
		["colorgy-test-account-459@test.colorgy.io", "colorgy-test-account-459"],
		["colorgy-test-account-460@test.colorgy.io", "colorgy-test-account-460"],
		["colorgy-test-account-461@test.colorgy.io", "colorgy-test-account-461"],
		["colorgy-test-account-462@test.colorgy.io", "colorgy-test-account-462"],
		["colorgy-test-account-463@test.colorgy.io", "colorgy-test-account-463"],
		["colorgy-test-account-464@test.colorgy.io", "colorgy-test-account-464"],
		["colorgy-test-account-465@test.colorgy.io", "colorgy-test-account-465"],
		["colorgy-test-account-466@test.colorgy.io", "colorgy-test-account-466"],
		["colorgy-test-account-467@test.colorgy.io", "colorgy-test-account-467"],
		["colorgy-test-account-468@test.colorgy.io", "colorgy-test-account-468"],
		["colorgy-test-account-469@test.colorgy.io", "colorgy-test-account-469"],
		["colorgy-test-account-470@test.colorgy.io", "colorgy-test-account-470"],
		["colorgy-test-account-471@test.colorgy.io", "colorgy-test-account-471"],
		["colorgy-test-account-472@test.colorgy.io", "colorgy-test-account-472"],
		["colorgy-test-account-473@test.colorgy.io", "colorgy-test-account-473"],
		["colorgy-test-account-474@test.colorgy.io", "colorgy-test-account-474"],
		["colorgy-test-account-475@test.colorgy.io", "colorgy-test-account-475"],
		["colorgy-test-account-476@test.colorgy.io", "colorgy-test-account-476"],
		["colorgy-test-account-477@test.colorgy.io", "colorgy-test-account-477"],
		["colorgy-test-account-478@test.colorgy.io", "colorgy-test-account-478"],
		["colorgy-test-account-479@test.colorgy.io", "colorgy-test-account-479"],
		["colorgy-test-account-480@test.colorgy.io", "colorgy-test-account-480"],
		["colorgy-test-account-481@test.colorgy.io", "colorgy-test-account-481"],
		["colorgy-test-account-482@test.colorgy.io", "colorgy-test-account-482"],
		["colorgy-test-account-483@test.colorgy.io", "colorgy-test-account-483"],
		["colorgy-test-account-484@test.colorgy.io", "colorgy-test-account-484"],
		["colorgy-test-account-485@test.colorgy.io", "colorgy-test-account-485"],
		["colorgy-test-account-486@test.colorgy.io", "colorgy-test-account-486"],
		["colorgy-test-account-487@test.colorgy.io", "colorgy-test-account-487"],
		["colorgy-test-account-488@test.colorgy.io", "colorgy-test-account-488"],
		["colorgy-test-account-489@test.colorgy.io", "colorgy-test-account-489"],
		["colorgy-test-account-490@test.colorgy.io", "colorgy-test-account-490"],
		["colorgy-test-account-491@test.colorgy.io", "colorgy-test-account-491"],
		["colorgy-test-account-492@test.colorgy.io", "colorgy-test-account-492"],
		["colorgy-test-account-493@test.colorgy.io", "colorgy-test-account-493"],
		["colorgy-test-account-494@test.colorgy.io", "colorgy-test-account-494"],
		["colorgy-test-account-495@test.colorgy.io", "colorgy-test-account-495"],
		["colorgy-test-account-496@test.colorgy.io", "colorgy-test-account-496"],
		["colorgy-test-account-497@test.colorgy.io", "colorgy-test-account-497"],
		["colorgy-test-account-498@test.colorgy.io", "colorgy-test-account-498"],
		["colorgy-test-account-499@test.colorgy.io", "colorgy-test-account-499"],
		["colorgy-test-account-500@test.colorgy.io", "colorgy-test-account-500"],
["test-yzu-student-f478@test.colorgy.io", "test-yzu-student-f478", "❌元智 學生"],
		["test-yuntech-student-ca62@test.colorgy.io", "test-yuntech-student-ca62", "❌雲科 學生"],
		["test-yuhing-student-44b4@test.colorgy.io", "test-yuhing-student-44b4", " ❌育英 學生"],
		["test-ytit-student-cfa1@test.colorgy.io", "test-ytit-student-cfa1", "❌ 永達 學生"],
		["test-ypu-student-5f3d@test.colorgy.io", "test-ypu-student-5f3d", "❌元培科大 學生"],
		["test-ym-student-bfe6@test.colorgy.io", "test-ym-student-bfe6", "❌ 陽明 學生"],
		["test-ydu-student-7a4e@test.colorgy.io", "test-ydu-student-7a4e", "❌育達 學生"],
		["test-wzu-student-b565@test.colorgy.io", "test-wzu-student-b565", "文藻 學生"],
		["test-wfu-student-23d8@test.colorgy.io", "test-wfu-student-23d8", "吳鳳科大 學生"],
		["test-vnu-student-0f6f@test.colorgy.io", "test-vnu-student-0f6f", "❌萬能科大 學生"],
		["test-utaipei-student-b364@test.colorgy.io", "test-utaipei-student-b364", "❌市北大 學生"],
		["test-usckh-student-72fe@test.colorgy.io", "test-usckh-student-72fe", "❌實踐高雄 學生"],
		["test-usc-student-22be@test.colorgy.io", "test-usc-student-22be", "❌實踐 學生"],
		["test-ukn-student-8776@test.colorgy.io", "test-ukn-student-8776", "❌康寧 學生"],
		["test-twu-student-f165@test.colorgy.io", "test-twu-student-f165", "❌環球科大 學生"],
		["test-tut-student-c911@test.colorgy.io", "test-tut-student-c911", "南應 學生"],
		["test-tust-student-7dde@test.colorgy.io", "test-tust-student-7dde", " 大華 學生"],
		["test-ttu-student-0b07@test.colorgy.io", "test-ttu-student-0b07", "大同 學生"],
		["test-ttc-student-30f0@test.colorgy.io", "test-ttc-student-30f0", "大同學院 學生"],
		["test-tsu-student-3963@test.colorgy.io", "test-tsu-student-3963", "首府 學生"],
		["test-tsint-student-359b@test.colorgy.io", "test-tsint-student-359b", "城市科大 學生"],
		["test-tpcu-student-c2d4@test.colorgy.io", "test-tpcu-student-c2d4", " 城市科大 學生"],
		["test-toko-student-ba96@test.colorgy.io", "test-toko-student-ba96", " 稻江 學生"],
		["test-tnua-student-a406@test.colorgy.io", "test-tnua-student-a406", " 北藝 學生"],
		["test-tnu-student-2432@test.colorgy.io", "test-tnu-student-2432", "東南科大 學生"],
		["test-tnnua-student-3eb5@test.colorgy.io", "test-tnnua-student-3eb5", "南藝大 學生"],
		["test-tmu-student-7cf8@test.colorgy.io", "test-tmu-student-7cf8", "北醫 學生"],
		["test-tku-student-a43d@test.colorgy.io", "test-tku-student-a43d", "淡江 學生"],
		["test-thu-student-0029@test.colorgy.io", "test-thu-student-0029", "東海 學生"],
		["test-tht-student-1d62@test.colorgy.io", "test-tht-student-1d62", "臺觀 學生"],
		["test-tf-student-5b5d@test.colorgy.io", "test-tf-student-5b5d", " 東方 學生"],
		["test-tcu-student-9ea4@test.colorgy.io", "test-tcu-student-9ea4", "慈濟 學生"],
		["test-tcpa-student-1b40@test.colorgy.io", "test-tcpa-student-1b40", " 戲曲 學生"],
		["test-tcmt-student-928d@test.colorgy.io", "test-tcmt-student-928d", " 北海 學生"],
		["test-tccn-student-36f5@test.colorgy.io", "test-tccn-student-36f5", " 慈濟學院 學生"],
		["test-takming-student-b50d@test.colorgy.io", "test-takming-student-b50d", "德明科大 學生"],
		["test-tajen-student-11b1@test.colorgy.io", "test-tajen-student-11b1", "大仁科大 學生"],
		["test-stut-student-00dc@test.colorgy.io", "test-stut-student-00dc", " 南台科大 學生"],
		["test-stust-student-6937@test.colorgy.io", "test-stust-student-6937", "南臺科大 學生"],
		["test-stu-student-c6d5@test.colorgy.io", "test-stu-student-c6d5", "樹德科大 學生"],
		["test-sju-student-9580@test.colorgy.io", "test-sju-student-9580", "聖約翰科大 學生"],
		["test-shu-student-2a6d@test.colorgy.io", "test-shu-student-2a6d", "世新 學生"],
		["test-scu-student-c5b1@test.colorgy.io", "test-scu-student-c5b1", "東吳 學生"],
		["test-pu-student-3af7@test.colorgy.io", "test-pu-student-3af7", " 靜宜 學生"],
		["test-pccu-student-8fb5@test.colorgy.io", "test-pccu-student-8fb5", " 文化 學生"],
		["test-oit-student-7988@test.colorgy.io", "test-oit-student-7988", "亞東 學生"],
		["test-ocu-student-557d@test.colorgy.io", "test-ocu-student-557d", "僑光 學生"],
		["test-nuu-student-0f5d@test.colorgy.io", "test-nuu-student-0f5d", "聯合 學生"],
		["test-nutn-student-2824@test.colorgy.io", "test-nutn-student-2824", " 南大 學生"],
		["test-nuk-student-ae2f@test.colorgy.io", "test-nuk-student-ae2f", "高大 學生"],
		["test-ntut-student-0d0d@test.colorgy.io", "test-ntut-student-0d0d", " 北科大 學生"],
		["test-ntust-student-33a6@test.colorgy.io", "test-ntust-student-33a6", "台科大 學生"],
		["test-ntue-student-e002@test.colorgy.io", "test-ntue-student-e002", " 北教大 學生"],
		["test-ntua-student-30be@test.colorgy.io", "test-ntua-student-30be", " 台藝大 學生"],
		["test-ntu-student-2f1d@test.colorgy.io", "test-ntu-student-2f1d", "台大 學生"],
		["test-nttu-student-31d5@test.colorgy.io", "test-nttu-student-31d5", " 東大 學生"],
		["test-ntsu-student-d10c@test.colorgy.io", "test-ntsu-student-d10c", " 國體 學生"],
		["test-ntpu-student-1760@test.colorgy.io", "test-ntpu-student-1760", " 北大 學生"],
		["test-ntpc-student-38dd@test.colorgy.io", "test-ntpc-student-38dd", " 海工 學生"],
		["test-ntou-student-b229@test.colorgy.io", "test-ntou-student-b229", " 海洋 學生"],
		["test-ntnu-student-50d8@test.colorgy.io", "test-ntnu-student-50d8", " 台師大 學生"],
		["test-ntit-student-b340@test.colorgy.io", "test-ntit-student-b340", " 中科大 學生"],
		["test-ntin-student-382d@test.colorgy.io", "test-ntin-student-382d", " 台南護專 學生"],
		["test-nthu-student-7589@test.colorgy.io", "test-nthu-student-7589", " 清大 學生"],
		["test-ntcu-student-9b40@test.colorgy.io", "test-ntcu-student-9b40", " 中教大 學生"],
		["test-ntcpe-student-470b@test.colorgy.io", "test-ntcpe-student-470b", "台體 學生"],
		["test-ntcnc-student-1e31@test.colorgy.io", "test-ntcnc-student-1e31", "中護 學生"],
		["test-ntcb-student-9ccf@test.colorgy.io", "test-ntcb-student-9ccf", " 北商 學生"],
		["test-nsysu-student-9649@test.colorgy.io", "test-nsysu-student-9649", "中山 學生"],
		["test-nqu-student-2bc0@test.colorgy.io", "test-nqu-student-2bc0", "金大 學生"],
		["test-npust-student-4fb5@test.colorgy.io", "test-npust-student-4fb5", "屏東科大 學生"],
		["test-nptu-student-e4a0@test.colorgy.io", "test-nptu-student-e4a0", " 屏大 學生"],
		["test-nou-student-2cf4@test.colorgy.io", "test-nou-student-2cf4", "空大 學生"],
		["test-nkut-student-e3a5@test.colorgy.io", "test-nkut-student-e3a5", " 南開 學生"],
		["test-nkuht-student-7269@test.colorgy.io", "test-nkuht-student-7269", "高餐 學生"],
		["test-nknu-student-37aa@test.colorgy.io", "test-nknu-student-37aa", " 高師大 學生"],
		["test-nkfust-student-c4ee@test.colorgy.io", "test-nkfust-student-c4ee", " 高第一 學生"],
		["test-njtc-student-56a1@test.colorgy.io", "test-njtc-student-56a1", " 南榮 學生"],
		["test-niu-student-c2c2@test.colorgy.io", "test-niu-student-c2c2", "宜大 學生"],
		["test-nhu-student-f3c1@test.colorgy.io", "test-nhu-student-f3c1", "南華 學生"],
		["test-nhcue-student-80a5@test.colorgy.io", "test-nhcue-student-80a5", "竹教 學生"],
		["test-nfu-student-b51c@test.colorgy.io", "test-nfu-student-b51c", "虎尾科大 學生"],
		["test-ndmctsgh-student-eebc@test.colorgy.io", "test-ndmctsgh-student-eebc", " 國防醫 學生"],
		["test-ndhu-student-4911@test.colorgy.io", "test-ndhu-student-4911", " 東華 學生"],
		["test-ncyu-student-1078@test.colorgy.io", "test-ncyu-student-1078", " 嘉大 學生"],
		["test-ncut-student-ccd3@test.colorgy.io", "test-ncut-student-ccd3", " 勤益科大 學生"],
		["test-ncue-student-b67c@test.colorgy.io", "test-ncue-student-b67c", " 彰師大 學生"],
		["test-ncu-student-f377@test.colorgy.io", "test-ncu-student-f377", "中央 學生"],
		["test-nctu-student-e46c@test.colorgy.io", "test-nctu-student-e46c", " 交大 學生"],
		["test-ncnu-student-9b2b@test.colorgy.io", "test-ncnu-student-9b2b", " 暨南 學生"],
		["test-ncku-student-6ca5@test.colorgy.io", "test-ncku-student-6ca5", " 成大 學生"],
		["test-nchu-student-6174@test.colorgy.io", "test-nchu-student-6174", " 中興 學生"],
		["test-nccu-student-e5a3@test.colorgy.io", "test-nccu-student-e5a3", " 政大 學生"],
		["test-nanya-student-1c9a@test.colorgy.io", "test-nanya-student-1c9a", "南亞 學生"]]
	@IBOutlet weak var testAccountTableView: UITableView!
	
    override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
		testAccountTableView.delegate = self
		testAccountTableView.dataSource = self
    }
	
	@IBAction func goBackToMainAccount() {
		self.statusLabel.text = "切換中..."
		ColorgyLogin.loginToFacebook { (token) -> Void in
			if let token = token {
				ColorgyLogin.loginToColorgyWithToken(token, handler: { (response, error) -> Void in
					ColorgyAPI.me({ (result) -> Void in
						UserSetting.storeAPIMeResult(result: result)
						self.statusLabel.text = "你現在是 \(UserSetting.UserPossibleOrganization())的學生"
						}, failure: { () -> Void in
							
					})
				})
			}
		}
	}


    // MARK: - Navigation

    // In a storyboard-based application, you will often want to do a little preparation before navigation
    override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
        // Get the new view controller using segue.destinationViewController.
        // Pass the selected object to the new view controller.
		if segue.identifier == "to chat room" {
			hidesBottomBarWhenPushed = true
			let vc = segue.destinationViewController as! ChatRoomViewController
			vc.userId = self.userId
			vc.uuid = self.uuid
//			vc.friendId = self.friendId
			vc.accessToken = self.accesstoken
		}
    }


}

extension TestChatLoginViewController : UITableViewDelegate, UITableViewDataSource {
	func numberOfSectionsInTableView(tableView: UITableView) -> Int {
		return 1
	}
	
	func tableView(tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
		return testAccounts.count
	}
	
	func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
		let cell = tableView.dequeueReusableCellWithIdentifier("test account", forIndexPath: indexPath)
		cell.textLabel?.text = testAccounts[indexPath.row][2] + " " + testAccounts[indexPath.row][0]
		return cell
	}
	
	func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
		tableView.deselectRowAtIndexPath(indexPath, animated: true)
		generalLogin(testAccounts[indexPath.row][0], p: testAccounts[indexPath.row][1])
	}
}
